---
  - name: Ensure iterm2 is installed
    homebrew_cask:
      name: iterm2

  - name: Add required homebrew repos
    homebrew_tap:
      name: homebrew/cask-fonts

  - name: Ensure console utils are installed
    homebrew:
      name:
        - bat
        - bfg
        - exa
        - doctl
        - fd
        - git
        - gnupg
        - go
        - grep
        - jsonlint
        - heroku
        - htop
        - httpie
        - hub
        - fzf
        - mosh
        - mtr
        - nmap
        - pinentry-mac
        - pipx
        - ripgrep
        - siege
        - starship
        - stern
        - telnet
        - wget
        - yamllint

  - name: Ensure graphical utils are installed
    homebrew_cask:
      name:
        - docker
        - font-source-code-pro
        - font-fira-code
        - font-hack-nerd-font
        - insomnia
        - ngrok
        - tableplus
        - visual-studio-code

  - name: Ensure python and node version managers are installed
    homebrew:
      name:
        - pyenv
        - n
