---
  - name: Ensure my productivity tools are installed
    homebrew_cask:
      name:
        - discord
        - firefox
        - iina
        - krisp
        - pocket-casts
        - protonvpn
        - slack
        - skype
        - spectacle
        - spotify
        - telegram
        - zoomus
